
steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/web:$SHORT_SHA", "."]
    # push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/web:$SHORT_SHA"]
    # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "$BRANCH_NAME",
        "--image=gcr.io/$PROJECT_ID/web:$SHORT_SHA",
        "--memory=1G",
        "--region=us-central1",
        "--platform=managed",
        "--allow-unauthenticated",
        "--set-env-vars", "apiKey=berglas://berglas-secrets-$PROJECT_ID/apiKey",
        "--set-env-vars", "authDomain=berglas://berglas-secrets-$PROJECT_ID/authDomain",
      ]
images:
  - gcr.io/$PROJECT_ID/web