version: '3.6'
services:
  next-app:
    image: node:12.6.0
    command: sh -c 'npm install && npm run start'
    working_dir: /app
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - ./app:/app
    environment:
      PORT: "8081"